# Generated by Django 3.1.1 on 2020-09-18 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slud',
            new_name='slug',
        ),
    ]
